<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit82f851e90ea9b729ec72e8d3385bc8c4
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Certificate_Builder\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Certificate_Builder\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit82f851e90ea9b729ec72e8d3385bc8c4', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Certificate_Builder\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit82f851e90ea9b729ec72e8d3385bc8c4', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Certificate_Builder\Composer\Autoload\ComposerStaticInit82f851e90ea9b729ec72e8d3385bc8c4::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \LearnDash\Certificate_Builder\Composer\Autoload\ComposerStaticInit82f851e90ea9b729ec72e8d3385bc8c4::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
